In [1]:
import pandas as pd
import numpy as np

In [11]:
data = pd.read_csv('soccer18m.csv')
data = data[data.Y < 18]
data['GameID'] = data.index
data['HomeWin'] = 1*(data['FTHG'] > data['FTAG'])
data.head()

,Div,Date,Y,HomeTeam,AwayTeam,FTHG,FTAG,HTHG,HTAG,HS,AS,HST,AST,pH,pD,pA,home_xG,away_xG,GameID,HomeWin
0,EPL,2014-08-16,14,Arsenal,Crystal Palace,2,1,1,1,14,4,6,2,0.778038,0.151989,0.069973,1.554110,0.158151,0,1
1,EPL,2014-08-16,14,Leicester,Everton,2,2,1,2,11,13,3,3,0.311972,0.289820,0.398208,1.278300,0.613273,1,0
2,EPL,2014-08-16,14,Man United,Swansea,1,2,0,1,14,5,5,4,0.715373,0.192169,0.092459,1.166350,0.278076,2,0
3,EPL,2014-08-16,14,QPR,Hull,0,1,0,0,19,11,6,4,0.395113,0.300577,0.304311,1.900670,1.117570,3,0
4,EPL,2014-08-16,14,Stoke,Aston Villa,0,1,0,0,12,7,2,2,0.502378,0.282316,0.215305,0.423368,0.909774,4,0

In [24]:
data['upset'] = np.where((data.pH < data.pA) & (data.HomeWin == 1),1, np.where((data.pA < data.pH) & (data.HomeWin == 0),1,0))
dataupset = data[data.upset == 1]

#dataupset['win_prob'] = np.where(data.HomeWin == 1, data.pH, data.pA)
#data1 = dataupset.nsmallest(7,'pH')
#data2 = dataupset.nsmallest(7,'pA')
upset = dataupset.nsmallest(7,'win_prob')

In [25]:
dataupset

,Div,Date,Y,HomeTeam,AwayTeam,FTHG,FTAG,HTHG,HTAG,HS,...,HST,AST,pH,pD,pA,home_xG,away_xG,GameID,HomeWin,upset
2,EPL,2014-08-16,14,Man United,Swansea,1,2,0,1,14,...,5,4,0.715373,0.192169,0.092459,1.166350,0.278076,2,0,1
3,EPL,2014-08-16,14,QPR,Hull,0,1,0,0,19,...,6,4,0.395113,0.300577,0.304311,1.900670,1.117570,3,0,1
4,EPL,2014-08-16,14,Stoke,Aston Villa,0,1,0,0,12,...,2,2,0.502378,0.282316,0.215305,0.423368,0.909774,4,0,1
5,EPL,2014-08-16,14,West Brom,Sunderland,2,2,1,1,10,...,5,2,0.443622,0.293534,0.262843,1.683430,0.991901,5,0,1
10,EPL,2014-08-23,14,Aston Villa,Newcastle,0,0,0,0,9,...,0,4,0.382789,0.291649,0.325562,0.507525,0.699295,10,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9104,La_Liga,2018-05-19,17,Leganes,Betis,3,2,1,1,8,...,3,8,0.352188,0.274034,0.373778,1.243820,1.800960,9104,1,1
9112,Ligue_1,2018-01-28,17,Bordeaux,Lyon,3,1,3,1,9,...,4,4,0.274672,0.273900,0.451428,2.424640,0.701990,9112,1,1
9116,Ligue_1,2018-04-20,17,Nantes,Rennes,1,1,1,0,13,...,7,9,0.421855,0.313339,0.264806,1.631570,0.911840,9116,0,1
9120,Ligue_1,2018-04-27,17,Montpellier,St Etienne,0,1,0,1,25,...,5,5,0.376633,0.308696,0.314671,1.324460,1.483270,9120,0,1
9122,Ligue_1,2018-04-29,17,Paris SG,Guingamp,2,2,0,1,14,...,3,5,0.877408,0.086146,0.036446,2.012640,2.203890,9122,0,1